Repository logfolio/OurBudgeting, pull requests merged in 2025-08, with the labels that each got.

#70 [자산관리] 자산관리 화면 UI
  app/build.gradle.kts
  app/src/main/java/com/fintern/ourbudgeting/ui/assetmanagement/component/AddAssetBody.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/assetmanagement/component/AddAssetButton.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/assetmanagement/component/AddAssetTopAppBar.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/assetmanagement/component/AssetBody.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/assetmanagement/component/AssetDevider.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/assetmanagement/component/AssetEditBody.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/assetmanagement/component/AssetEditTopAppBar.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/assetmanagement/component/AssetTitle.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/assetmanagement/component/AssetTopAppBar.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/assetmanagement/component/AssetTopSection.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/assetmanagement/component/StatisticAssetChartTitle.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/assetmanagement/component/StatisticAssetTopAppBar.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/assetmanagement/component/StatisticAssetTopSection.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/assetmanagement/screen/AddAssetManagement.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/assetmanagement/screen/AssetEditManagement.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/assetmanagement/screen/AssetManagement.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/assetmanagement/screen/StatisticAssetManagement.kt
  app/src/main/res/drawable/ic_arrowback.xml
  app/src/main/res/drawable/ic_delete.xml
  app/src/main/res/drawable/ic_edit.xml
  app/src/main/res/drawable/ic_graph.xml
  app/src/main/res/drawable/ic_navigate_before.xml
  app/src/main/res/drawable/ic_navigate_next.xml
  app/src/main/res/drawable/ic_plus.xml
  app/src/main/res/values/strings.xml
Labels: feature

#72 [수입/지출 관리] 수입 / 지출 UI 구현
  app/build.gradle.kts
  app/src/main/java/com/fintern/ourbudgeting/ui/common/model/TransactionType.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/save/TransactionAddScreen.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/save/TransactionAddUiState.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/save/TransactionAddViewModel.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/save/componenet/CommonOutlinedTextField.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/save/componenet/DatePickerField.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/save/componenet/DropDownField.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/save/componenet/ImagePreview.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/save/componenet/TransactionToggle.kt
  app/src/main/java/com/fintern/ourbudgeting/util/NumberUtils.kt
  app/src/main/res/drawable/ic_camera.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: feature

#71 [캘린더] 거래 내역 필터링
  app/src/main/java/com/fintern/ourbudgeting/data/calendar/Category.kt
  app/src/main/java/com/fintern/ourbudgeting/data/repository/RemoteTransactionRepository.kt
  app/src/main/java/com/fintern/ourbudgeting/data/repository/TransactionRepository.kt
  app/src/main/java/com/fintern/ourbudgeting/di/RepositoryModule.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/calendar/CalendarScreen.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/calendar/TransactionViewModel.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/calendar/component/Calendar.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/calendar/component/CalendarDay.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/calendar/component/CalendarFilterControls.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/calendar/component/CalendarTransactionFilter.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/calendar/component/CategoryItemListItem.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/calendar/component/FilterBottomSheet.kt
  app/src/main/res/values/strings.xml
Labels: feature

#76 [회원 관리] Context를 ViewModel 및 Repository에 전달하지 않도록 수정
  app/src/main/java/com/fintern/ourbudgeting/data/auth/GoogleSignInClient.kt
  app/src/main/java/com/fintern/ourbudgeting/data/repository/GoogleAuthRepository.kt
  app/src/main/java/com/fintern/ourbudgeting/di/AuthModule.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/login/LoginScreen.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/login/LoginViewModel.kt
Labels: feature, pair

#77 [UI] 네비게이션 바
  app/src/main/java/com/fintern/ourbudgeting/MainActivity.kt
  app/src/main/java/com/fintern/ourbudgeting/navigation/AppNavHost.kt
  app/src/main/java/com/fintern/ourbudgeting/navigation/AppNavigationBar.kt
  app/src/main/java/com/fintern/ourbudgeting/navigation/BottomNavigationItem.kt
  app/src/main/java/com/fintern/ourbudgeting/navigation/Screen.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/login/HomeScreen.kt
  app/src/main/res/drawable/ic_asset.xml
  app/src/main/res/drawable/ic_calendar.xml
  app/src/main/res/drawable/ic_home.xml
  app/src/main/res/drawable/ic_setting.xml
  app/src/main/res/drawable/ic_statistic.xml
  app/src/main/res/values/strings.xml
Labels: feature, pair

#75 [수입/지출 관리] Firebase 저장
  app/build.gradle.kts
  app/src/main/java/com/fintern/ourbudgeting/data/repository/RemoteTransactionSaveRepository.kt
  app/src/main/java/com/fintern/ourbudgeting/data/repository/TransactionRepository.kt
  app/src/main/java/com/fintern/ourbudgeting/di/FirebaseModule.kt
  app/src/main/java/com/fintern/ourbudgeting/di/TransactionModule.kt
  app/src/main/java/com/fintern/ourbudgeting/navigation/AppNavHost.kt
  app/src/main/java/com/fintern/ourbudgeting/navigation/Screen.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/common/model/FirebaseError.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/save/TransactionSaveScreen.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/save/TransactionSaveUiState.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/save/TransactionSaveViewModel.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/statistics/chart/StatisticsUiState.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/statistics/chart/StatisticsViewModel.kt
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: feature

#79 [수입/지출 관리] 영수증 스캔
  app/build.gradle.kts
  app/src/main/java/com/fintern/ourbudgeting/navigation/AppNavHost.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/save/TransactionSaveScreen.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/save/TransactionSaveViewModel.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/save/componenet/TransactionSaveTopAppBar.kt
  app/src/main/java/com/fintern/ourbudgeting/util/ReceiptOcrParser.kt
  app/src/main/res/drawable/ic_mic.xml
  app/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: feature

#78 [캘린더] 날짜 선택 및 필터링 구분
  app/src/main/java/com/fintern/ourbudgeting/ui/calendar/CalendarScreen.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/calendar/component/Calendar.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/calendar/component/CalendarDay.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/calendar/extensions/LocalDateExtensions.kt
Labels: feature

#81 [자산관리] 자산 유형 수정 화면 UI 구현 및 실데이터 연결
  app/src/main/java/com/fintern/ourbudgeting/data/repository/AssetAdditionRepository.kt
  app/src/main/java/com/fintern/ourbudgeting/data/repository/AssetEditRepository.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/assetmanagement/assetdisplay/AssetDisplayScreen.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/assetmanagement/assetdisplay/AssetDisplayViewModel.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/assetmanagement/assetdisplay/component/AssetTopSection.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/assetmanagement/assetedition/AssetEditScreen.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/assetmanagement/assetedition/AssetEditUiState.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/assetmanagement/assetedition/AssetEditViewModel.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/assetmanagement/assetedition/component/AssetEditBody.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/assetmanagement/assetedition/component/AssetEditTopAppBar.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/assetmanagement/assetedition/component/AssetTypeListTitle.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/assetmanagement/assettypeaddition/AssetAdditionScreen.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/assetmanagement/assettypeaddition/AssetAdditionViewModel.kt
  app/src/main/res/drawable/ic_check.xml
  app/src/main/res/drawable/ic_close.xml
  app/src/main/res/values/strings.xml
Labels: feature

#82 [홈화면]이동시 households 및 기본 값 설정
  app/src/main/java/com/fintern/ourbudgeting/data/repository/AssetAdditionRepository.kt
  app/src/main/java/com/fintern/ourbudgeting/data/repository/AssetEditRepository.kt
  app/src/main/java/com/fintern/ourbudgeting/data/repository/HouseholdRepository.kt
  app/src/main/java/com/fintern/ourbudgeting/di/UserModule.kt
  app/src/main/java/com/fintern/ourbudgeting/navigation/AppNavHost.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/assetmanagement/assettypeaddition/AssetAdditionScreen.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/common/model/Households.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/login/HomeScreen.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/user/UserViewModel.kt
Labels: feature

#87 환율 api 받아오기 위한 네트워크 통신 코드 구현
  app/build.gradle.kts
  app/src/main/java/com/fintern/ourbudgeting/data/api/ExchangeRateApiService.kt
  app/src/main/java/com/fintern/ourbudgeting/data/model/ExchangeRate.kt
  app/src/main/java/com/fintern/ourbudgeting/data/repository/ExchangeRateRepository.kt
  app/src/main/java/com/fintern/ourbudgeting/di/NetworkModule.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/login/HomeViewModel.kt
  build.gradle.kts
  gradle/libs.versions.toml
Labels: feature, pair

#91 [홈] 홈 화면 UI 구현
  app/build.gradle.kts
  app/src/main/java/com/fintern/ourbudgeting/data/model/ExchangeRate.kt
  app/src/main/java/com/fintern/ourbudgeting/data/repository/ExchangeRateRepository.kt
  app/src/main/java/com/fintern/ourbudgeting/navigation/AppNavHost.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/home/HomeScreen.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/home/HomeUiState.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/home/HomeViewModel.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/home/components/AssetSummaryCard.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/home/components/ExchangeRateCard.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/home/components/LatestTransactionCard.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/login/HomeScreen.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/login/HomeViewModel.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/save/TransactionSaveScreen.kt
  app/src/main/java/com/fintern/ourbudgeting/util/CurrencyFilter.kt
  app/src/main/res/values/strings.xml
Labels: feature

#94 [캘린더] Firestore 값 받아오기
  app/src/main/java/com/fintern/ourbudgeting/data/calendar/Category.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/calendar/CalendarScreen.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/calendar/component/CalendarAccountAndUser.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/calendar/component/CalendarButton.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/calendar/component/CategoryItemListItem.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/calendar/component/CategoryListSection.kt
  app/src/main/res/values/strings.xml
Labels: feature

#98 [홈] 최근 거래 내역을 표시
  app/build.gradle.kts
  app/src/main/java/com/fintern/ourbudgeting/data/calendar/Category.kt
  app/src/main/java/com/fintern/ourbudgeting/data/repository/RemoteLatestTransactionRepository.kt
  app/src/main/java/com/fintern/ourbudgeting/data/repository/TransactionRepository.kt
  app/src/main/java/com/fintern/ourbudgeting/di/HomeModule.kt
  app/src/main/java/com/fintern/ourbudgeting/navigation/AppNavHost.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/home/HomeScreen.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/home/HomeViewModel.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/home/components/LatestTransactionCard.kt
  app/src/main/res/drawable/ic_warning.xml
  gradle/libs.versions.toml
Labels: feature

#100 [홈] 현재 잔액 표시
  app/src/main/java/com/fintern/ourbudgeting/data/model/FirebaseConstants.kt
  app/src/main/java/com/fintern/ourbudgeting/data/repository/RemoteTotalAmountRepository.kt
  app/src/main/java/com/fintern/ourbudgeting/data/repository/TotalAmountRepository.kt
  app/src/main/java/com/fintern/ourbudgeting/di/TotalAmountModule.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/home/HomeScreen.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/home/HomeUiState.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/home/HomeViewModel.kt
Labels: feature

#105 [자산관리] 화면이동 코드 추가 및 TopAppbar 간격 수정
  app/src/main/java/com/fintern/ourbudgeting/navigation/AppNavHost.kt
  app/src/main/java/com/fintern/ourbudgeting/navigation/Screen.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/assetmanagement/assetdisplay/component/AssetDisplayTopAppBar.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/assetmanagement/assetedition/component/AssetEditTopAppBar.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/assetmanagement/assettypeaddition/component/AssetAdditionTopAppBar.kt
Labels: feature

#107 [수입/지출 관리] 수입/지출 내용 알 수 없는 오류 해결
  app/src/main/java/com/fintern/ourbudgeting/navigation/AppNavHost.kt
Labels: bug

#115 [캘린더] 닉네임 데이터 가져오기
  app/src/main/java/com/fintern/ourbudgeting/ui/calendar/CalendarScreen.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/calendar/component/CategoryItemListItem.kt
Labels: feature

#117 [수입/지출 관리] 카테고리를 영어로 저장
  app/src/main/java/com/fintern/ourbudgeting/data/repository/RemoteTransactionSaveRepository.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/save/TransactionSaveScreen.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/save/TransactionSaveUiState.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/save/TransactionSaveViewModel.kt
Labels: bug

#121 [설정] nickname, email 값 받아오기
  app/src/main/java/com/fintern/ourbudgeting/navigation/AppNavHost.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/setting/SettingScreen.kt
Labels: feature

#119 [수입/지출 관리] 사용자의 자산 유형 표시
  app/src/main/java/com/fintern/ourbudgeting/data/repository/RemoteTransactionSaveRepository.kt
  app/src/main/java/com/fintern/ourbudgeting/data/repository/TransactionRepository.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/save/TransactionSaveScreen.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/save/TransactionSaveUiState.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/save/TransactionSaveViewModel.kt
Labels: feature

#124 [자산관리] firebase householdId 중복생성 방지 코드 구현
  app/src/main/java/com/fintern/ourbudgeting/data/repository/HouseholdRepository.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/home/HomeScreen.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/user/UserViewModel.kt
Labels: feature

#125 [수입/지출 관리] UI 레이아웃 수정
  app/src/main/java/com/fintern/ourbudgeting/ui/save/TransactionSaveScreen.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/save/componenet/TransactionSaveTopAppBar.kt
  app/src/main/res/values/strings.xml
Labels: fix

#127 [자산관리] 자산관리화면 refactor
  app/src/main/java/com/fintern/ourbudgeting/navigation/AppNavigationBar.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/assetmanagement/assetdisplay/component/FABMenuItem.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/assetmanagement/assettypeaddition/AssetAdditionScreen.kt
Labels: fix

#128 [캘린더] 화면 스크롤
  app/src/main/java/com/fintern/ourbudgeting/ui/calendar/CalendarGrid.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/calendar/CalendarScreen.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/calendar/component/Calendar.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/calendar/component/CategoryListSectionItem.kt
  app/src/main/res/values/strings.xml
Labels: feature

#130 [Fix] Warning에 대한 코드 수정
  app/build.gradle.kts
  app/src/main/java/com/fintern/ourbudgeting/data/repository/AssetEditRepository.kt
  app/src/main/java/com/fintern/ourbudgeting/navigation/BottomNavigationItem.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/assetmanagement/assettypeaddition/AssetTypeUiState.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/calendar/component/CalendarTransactionFilter.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/common/model/FirebaseError.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/common/model/TransactionType.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/home/HomeUiState.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/save/TransactionSaveUiState.kt
  app/src/main/java/com/fintern/ourbudgeting/ui/statistics/chart/model/StatisticsTab.kt
Labels: fix

#131 [Fix] release, debug 설정
  app/build.gradle.kts
Labels: fix
